name: Publish public branch to public repository
on:
  push:
    branches:
      - public
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            public-env
            private-env
          permission-contents: write
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Add public repository origin
        run: |
          git remote add public https://github.com/appare45/public-env.git
      - name: Push public branch to public repository
        run: |
          git push -u public public
