name: Publish public branch to public repository
on:
  push:
    branches:
      - public
jobs:
  job:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Add public repository origin
        run: |
          git remote add public https://github.com/appare45/env.git
      - name: Push public branch to public repository
        run: |
          git push -u public public
